# Numerical python (numpy)

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

## Creating arrays

In [2]:
import numpy as np

Let's define a list of numbers:

In [4]:
l = [1.0, 2.0, 0.0, 3.0]
print(type(l))
l

<class 'list'>


[1.0, 2.0, 0.0, 3.0]

Now let's convert this list to a numpy array:

In [5]:
a = np.array(l)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 0., 3.])

We can also create lists of lists...

In [6]:
l = [[1.1, 5.3, 2.1, 6.5], [4.3, 2.3, 1.8, 7.3]]
l

[[1.1, 5.3, 2.1, 6.5], [4.3, 2.3, 1.8, 7.3]]

...and convert them to 2d arrays (matrices):

In [7]:
m = np.array(l)
m

## The shape of an array

To get the size of an array, we can use the `shape` function:

In [47]:
m.shape

(2, 4)

`shape` returns a `tuple`(a list that cannot be modified). For a two-dimensional matrix, the elements of the tuple are the numbers of rows and columns of the matrix.

Note that we can also create higher-dimensional matrices:

In [64]:
h = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
])
print(h)
print('Shape of h:', h.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of h: (2, 2, 2)


## Accessing elements

In [61]:
print('Access second element of a vector')
print('a = ', a)
print('a[1] = ', a[1])
print()

print('Select a row in a matrix')
print("m = ", m)
print('m[0] = ', m[0])
print('m[0, :] = ', m[0, :])
print()

print('Select second element in first row')
print('m[0,1] = ', m[0,1])
print()
print('select second column')
print('m[:,1] = ', m[:,1])
print()

print('select first sub-matrix of higher-dimensional matrix')
print(h)
print('h[0] = ', h[0])

Access second element of a vector
a =  [4 3 2 6 5 4]
a[1] =  3

Select a row in a matrix
m =  [[1.1 5.3 2.1 6.5]
 [4.3 2.3 1.8 7.3]]
m[0] =  [1.1 5.3 2.1 6.5]
m[0, :] =  [1.1 5.3 2.1 6.5]

Select second element in first row
m[0,1] =  5.3

select second column
m[:,1] =  [5.3 2.3]

select first sub-matrix of higher-dimensional matrix
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
h[0] =  [[1 2]
 [3 4]]


## Operations on arrays

In [9]:
print('sum of all elements in array', a.sum())

sum of all elements in array 6.0


In [10]:
print('mean of elements in array', a.mean())

mean of elements in array 1.5


In [11]:
# scalar operations
a = np.array([1.,2.,3.,4.])
print(a + 3)
print(a - 1)
print(a * 5)
print(a / 4)

[4. 5. 6. 7.]
[0. 1. 2. 3.]
[ 5. 10. 15. 20.]
[0.25 0.5  0.75 1.  ]


In [12]:
# pointwise operations between two vectors/matrices
a = np.array([1.,2.,3.,4.])
b = np.array([5.,6.,7.,8.])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[ 6.  8. 10. 12.]
[-4. -4. -4. -4.]
[ 5. 12. 21. 32.]
[0.2        0.33333333 0.42857143 0.5       ]


### Dot product

The dot product between two vectors is defined as

$$ \vec{a} \cdot \vec{b} = \sum_{i=0}^{n} \vec{a}_i \vec{b}_i  $$

In [13]:
a = np.array([1.,2.,3.,4.])
b = np.array([5.,6.,7.,8.])

np.dot(a, b) # np.sum(a*b)

70.0

### Matrix product

$$ A  B_{ij} = \sum_{k=0}^m A_{ik} A_{kj}$$

In [14]:
A = np.array([[1.,2.,3.,4.], [1.,2.,3.,4.]])
B = np.array([[5.,6.,7.,8.], [5.,6.,7.,8.]])

A @ B.transpose() # np.dot(A, B.transpose())

array([[70., 70.],
       [70., 70.]])

## More statistics

### Min/max on array

In [51]:
(a.min(), a.max())

### and on matrix

In [62]:
(m.min(), m.max())

(1.1, 7.3)

In [53]:
(m.min(axis=0), m.max(axis=0))

(array([1.1, 2.3, 1.8, 6.5]), array([4.3, 5.3, 2.1, 7.3]))

In [54]:
(m.min(axis=1), m.max(axis=1))

(array([1.1, 1.8]), array([6.5, 7.3]))

### Mean/variance/std deviation

In [56]:
a.mean()

2.5

In [57]:
a.var()

1.25

In [61]:
a.std() # std deviation is equal to np.sqrt(a.var())

1.118033988749895

## Comparisons between arrays

In [65]:
a = np.array([9.1, 2.1, 5.4, 3.2])
b = np.array([8.4, 2.1, 4.3, 6.5])
a == b

array([False,  True, False, False])

## Complex indexing/slicing

In [30]:
a = np.array([4,3,2,6,5,4])

We could loop over an array in a loop:

In [71]:
# select a range
a[1:4]

array([3, 2, 6])

In [72]:
# could be also written as
a[[1,2,3]]

array([3, 2, 6])

Select the second, fourth, and sixth element

```python
array[start:stop:stride]
```

`stride` determines how far the index jumps.

In [33]:
a[1::2]

array([3, 6, 4])

## Exercises

### 1. 

Suppose you have to points `a = np.array([2.1, 4.2, 7.2])` and `b=([8.3, 9.1, 3.2])`. Write a program that calculates the euclidean distance between them.

Euclidean distance between two vectors is defined as
$$ d(\vec{a},\vec{b}) = \sqrt{\sum_{i=0}^{n} (a_i-b_i)^2} $$

use the numpy function `np.sqrt` and `np.power`.

### 2.

Generate a matrix of shaped `(3,4)` of random numbers with the function `np.random`.

- Calculate the product (hint: use the `@` operator) between this matrix and the column vector `np.array([1,2,3,4])`.

- Calculate the square of the random matrix (multiply the matrix by its transpose). A matrix can be transposed (rotated) with the function `m.transpose()`.