# Numerical python (numpy)

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.

In [1]:
import numpy as np

In [4]:
l = [1.0, 2.0, 0.0, 3.0]
print(type(l))
l

<class 'list'>


[1.0, 2.0, 0.0, 3.0]

In [5]:
a = np.array(l)
print(type(a))
a

<class 'numpy.ndarray'>


array([1., 2., 0., 3.])

In [9]:
l = [[1.1, 5.3, 2.1, 6.5], [4.3, 2.3, 1.8, 7.3]]
l

[[1.1, 5.3, 2.1, 6.5], [4.3, 2.3, 1.8, 7.3]]

In [33]:
m = np.array(l)
m

array([[1.1, 5.3, 2.1, 6.5],
       [4.3, 2.3, 1.8, 7.3]])

In [47]:
# accessing elements
print('first element in array', a[1])
print('one index selects whole row', m[0])
print('same', m[0, :])
print('select second element in first row', m[0,1])
print('select second column', m[:,1])

first element in array 1.0
one index selects whole row [1.1 5.3 2.1 6.5]
same [1.1 5.3 2.1 6.5]
select second element in first row 5.3
select second column [5.3 2.3]


In [48]:
print('sum of all elements in array', a.sum())

In [49]:
print('mean of elements in array', a.mean())

mean of elements in array 1.5


In [16]:
# scalar operations
a = np.array([1.,2.,3.,4.])
print(a + 3)
print(a - 1)
print(a * 5)
print(a / 4)

[4. 5. 6. 7.]
[ 5. 10. 15. 20.]
[0.25 0.5  0.75 1.  ]


In [17]:
# pointwise operations between two vectors/matrices
a = np.array([1.,2.,3.,4.])
b = np.array([5.,6.,7.,8.])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

# Dot product

In [55]:
a = np.array([1.,2.,3.,4.])
b = np.array([5.,6.,7.,8.])

np.dot(a, b) # np.sum(a*b)

70.0

# Matrix product

In [26]:
a = np.array([[1.,2.,3.,4.], [1.,2.,3.,4.]])
b = np.array([[5.,6.,7.,8.], [5.,6.,7.,8.]])

a @ b.transpose() # np.dot(a, b.transpose())

array([[70., 70.],
       [70., 70.]])

# More statistics

## Min/max on array

In [51]:
(a.min(), a.max())

## and on matrix

In [62]:
(m.min(), m.max())

(1.1, 7.3)

In [53]:
(m.min(axis=0), m.max(axis=0))

(array([1.1, 2.3, 1.8, 6.5]), array([4.3, 5.3, 2.1, 7.3]))

In [54]:
(m.min(axis=1), m.max(axis=1))

(array([1.1, 1.8]), array([6.5, 7.3]))

# Mean/variance/std deviation

In [56]:
a.mean()

2.5

In [57]:
a.var()

1.25

In [61]:
a.std() # std deviation is equal to np.sqrt(a.var())

1.118033988749895

# Comparisons between arrays

In [65]:
a = np.array([9.1, 2.1, 5.4, 3.2])
b = np.array([8.4, 2.1, 4.3, 6.5])
a == b

array([False,  True, False, False])

# Complex indexing/slicing

In [67]:
a = np.array([4,3,2,6,5,4])

In [71]:
# select a range
a[1:4]

array([3, 2, 6])

In [72]:
# could be also written as
a[[1,2,3]]

array([3, 2, 6])